// import { Inter } from 'next/font/google'
// import './globals.css'
// import Footer from '@/components/Footer/Footer'
// import Navigation from '@/components/Navigation'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <CartProvider>
//         <Navigation/>
//         {children}
//         {/* <Footer/> */}
//         </CartProvider>
//         </body>
//     </html>
//   )
// }

import "./globals.css";
import { dir } from "i18next";
import { languages } from "../i18n/settings";
import { Montserrat } from "next/font/google";
import { CartProvider } from "../lib/react-use-cart";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer/Footer";
// import { LangSwitch } from "./components/Langswitch/client";
const inter = Montserrat({
  weight: "500",
  display: "swap",
  subsets: ["vietnamese"],
});const metadata = {
  title: {
    default: "Pastry",
    template: `Pastry`,
  },
  description: "Pastry description",
};export async function generateMetadata() {
  return metadata;
}
const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
};
export async function generateViewport() {
  return viewport;
}export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}
function RootLayout({ children, params: { lng } }) {
  return (
    <html lang={lng} dir={dir(lng)}>
      <head></head>
      <body>
        {/* <LangSwitch lng={lng} /> */}
        <CartProvider>
        <Navigation/>
        {children}
        <Footer/>
        </CartProvider>
        
      </body>
    </html>
  );
}
export default RootLayout;
